name: alice_http_client
description: "Alice + HTTP Client integration. It contains plugin for Alice which allows to use Http Client."
version: 1.0.6
repository: https://github.com/jhomlala/alice
homepage: https://github.com/jhomlala/alice
publish_to: none
topics:
  - http
  - inspector
  - alice
  - interceptor

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  alice:
    git:
      url: https://github.com/avinashk369/alice.git
      path: packages/alice  # Specify the path to the package
      ref: master

dev_dependencies:
  flutter_lints: ^4.0.0